name: jsaver
description: Save Files Plugin By Just Codes Developers.
version: 0.0.1
homepage: https://github.com/AymanYassin/
repository: https://github.com/AymanYassin/JSaver

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  plugin:
    platforms:
      android:
        package: com.jucodes.jsaver
        pluginClass: JSaverPlugin

