name: jsaver
description: Save Files Plugin By Just Codes Developers, JSaver is a plugin that save files in internal or external directories for android.
version: 0.0.4
homepage: https://github.com/AymanYassinn/
repository: https://github.com/AymanYassinn/JSaver

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  plugin:
    platforms:
      android:
        package: com.jucodes.jsaver
        pluginClass: JSaverPlugin

