name: jsaver
description: Just An Amazing File Saver Plugin That Save Files To User Choice Directory On Android , Web , Linux & Windows.
version: 1.3.0
homepage: https://github.com/AymanYassinn/
repository: https://github.com/AymanYassinn/JSaver

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  ffi: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.jucodes.jsaver
        pluginClass: JSaverPlugin
      linux:
        default_package: jsaver
      windows:
        default_package: jsaver
      web:
        pluginClass: JSaverWeb
        fileName:  _web/jSaver_web.dart

